package ru.valentin.exception.attachment

class AttachmentIOException(cause : Throwable)
    : RuntimeException(cause) {
}